/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_svgbuilder_free(a: number): void;
export function svgbuilder_new(): number;
export function svgbuilder_margin(a: number, b: number): number;
export function svgbuilder_unit(a: number, b: number): number;
export function svgbuilder_fg_module_size(a: number, b: number): number;
export function svgbuilder_bg_module_size(a: number, b: number): number;
export function svgbuilder_finder_pattern(a: number, b: number): number;
export function svgbuilder_finder_roundness(a: number, b: number): number;
export function svgbuilder_foreground(a: number, b: number, c: number): number;
export function svgbuilder_background(a: number, b: number, c: number): number;
export function svgbuilder_toggle_render(a: number, b: number): number;
export function svgbuilder_toggle_scale(a: number, b: number): number;
export function svgbuilder_render(a: number, b: number): number;
export function svgbuilder_scale(a: number, b: number): number;
export function svgbuilder_toggle(a: number, b: number): number;
export function svgbuilder_get(a: number, b: number): number;
export function __wbg_version_free(a: number): void;
export function __wbg_get_version_0(a: number): number;
export function __wbg_set_version_0(a: number, b: number): void;
export function version_new(a: number): number;
export function __wbg_qroptions_free(a: number): void;
export function qroptions_new(): number;
export function qroptions_min_version(a: number, b: number): number;
export function qroptions_min_ecl(a: number, b: number): number;
export function qroptions_mode(a: number, b: number): number;
export function qroptions_mask(a: number, b: number): number;
export function __wbg_svgresult_free(a: number): void;
export function __wbg_get_svgresult_svg(a: number, b: number): void;
export function __wbg_set_svgresult_svg(a: number, b: number, c: number): void;
export function __wbg_get_svgresult_mode(a: number): number;
export function __wbg_set_svgresult_mode(a: number, b: number): void;
export function __wbg_get_svgresult_ecl(a: number): number;
export function __wbg_set_svgresult_ecl(a: number, b: number): void;
export function __wbg_get_svgresult_version(a: number): number;
export function __wbg_set_svgresult_version(a: number, b: number): void;
export function __wbg_get_svgresult_mask(a: number): number;
export function __wbg_set_svgresult_mask(a: number, b: number): void;
export function get_svg(a: number, b: number, c: number, d: number, e: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
