/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_matrix_free(a: number): void;
export function __wbg_get_matrix_value(a: number, b: number): void;
export function __wbg_set_matrix_value(a: number, b: number, c: number): void;
export function __wbg_get_matrix_width(a: number): number;
export function __wbg_set_matrix_width(a: number, b: number): void;
export function __wbg_get_matrix_version(a: number): number;
export function __wbg_set_matrix_version(a: number, b: number): void;
export function __wbg_get_matrix_ecl(a: number): number;
export function __wbg_set_matrix_ecl(a: number, b: number): void;
export function __wbg_get_matrix_mask(a: number): number;
export function __wbg_set_matrix_mask(a: number, b: number): void;
export function __wbg_qroptions_free(a: number): void;
export function qroptions_new(): number;
export function qroptions_min_version(a: number, b: number): number;
export function qroptions_min_ecl(a: number, b: number): number;
export function qroptions_mode(a: number, b: number): number;
export function qroptions_mask(a: number, b: number): number;
export function __wbg_svgoptions_free(a: number): void;
export function svgoptions_new(): number;
export function svgoptions_margin(a: number, b: number): number;
export function svgoptions_unit(a: number, b: number): number;
export function svgoptions_foreground(a: number, b: number, c: number): number;
export function svgoptions_background(a: number, b: number, c: number): number;
export function svgoptions_scale_x_matrix(a: number, b: number, c: number): number;
export function svgoptions_scale_y_matrix(a: number, b: number, c: number): number;
export function svgoptions_scale_matrix(a: number, b: number, c: number): number;
export function svgoptions_toggle(a: number, b: number): number;
export function __wbg_svgresult_free(a: number): void;
export function __wbg_get_svgresult_svg(a: number, b: number): void;
export function __wbg_set_svgresult_svg(a: number, b: number, c: number): void;
export function __wbg_get_svgresult_mode(a: number): number;
export function __wbg_set_svgresult_mode(a: number, b: number): void;
export function __wbg_get_svgresult_ecl(a: number): number;
export function __wbg_set_svgresult_ecl(a: number, b: number): void;
export function __wbg_get_svgresult_version(a: number): number;
export function __wbg_set_svgresult_version(a: number, b: number): void;
export function __wbg_get_svgresult_mask(a: number): number;
export function __wbg_set_svgresult_mask(a: number, b: number): void;
export function get_matrix(a: number, b: number, c: number, d: number): void;
export function get_svg(a: number, b: number, c: number, d: number, e: number): void;
export function __wbg_version_free(a: number): void;
export function __wbg_get_version_0(a: number): number;
export function __wbg_set_version_0(a: number, b: number): void;
export function version_new(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
